import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by esbuild for the POS multi-tab browser harness; rebuilt on
    // demand, never edited by hand. See lib/pos/__tests__/browser/.
    "lib/pos/__tests__/browser/*.bundle.js",
  ]),
]);

export default eslintConfig;
